### ISSUE TITLE
Links in Documentation is Outdated and 404's

### ISSUE THREAD

**Issue by jack-fleenor** [maxio-com/ab-golang-sdk#29]
Trying to read the documentation on testing and watching the tutorials are impacted by 404'ing URLs.

**Comment by michalpierog** [comment]
Hi @jack-fleenor, can you provide example link which is not working and page containing it? Or did you use some bookmark in your browser/link from browser history?

**Comment by jack-fleenor** [comment]
Well, I can't find them again haha. So I am closing the issue.
